added DOSCAR.LSO.lobster file attribute to Lobsterout, updated tests
materialsproject/pymatgen pull request #2795
Opened 2023-01-09 11:48 UTC by naik-aakash

## Lobsterout.get_doc() method updated

- Added has_doscar_lso: bool attribute to Lobsterout (checks if DOSCAR.LSO.lobster file is written during lobster run) 
- Updated corresponding tests

2023-01-09 12:07 UTC, naik-aakash commented
Hi @janosh ,This PR is ready to be merged. Thanks !!

2023-01-09 14:22 UTC, janosh requested changes
Looks good! Just one comment about the test

2023-01-09 17:28 UTC, janosh commented on pymatgen/io/lobster/tests/test_lobster.py
Please always use existing test files if possible.

2023-01-10 09:35 UTC, naik-aakash commented on pymatgen/io/lobster/tests/test_lobster.py
Thanks. I updated the test to test False on another file, as per your suggestion

2023-01-10 14:11 UTC, merged

2023-01-10 14:11 UTC, janosh commented
Thanks!