[WIP] revise MatPESStaticSet, inherit from DictSet
materialsproject/pymatgen pull request #3278
Opened 2023-08-28 21:42 UTC by SophiaRuan

## Summary

Major changes:

- feature 1: Revise MatPESStaticSet, inherit from DictSet

## Todos

Check if the previous Incar will override the default MatPESStaticSet Incar.
Check if the new settings added by Custodian will be updated.

## Checklist

- [ ] Google format doc strings added. Check with `ruff`.
- [ ] Type annotations included. Check with `mypy`.
- [ ] Tests added for new features/fixes.
- [ ] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

2023-08-28 22:38 UTC, janosh requested changes
Thanks for the quick followup to https://github.com/materialsproject/pymatgen/pull/3254! 👍 

Perhaps you're already aware but the tests need updating.

2023-08-28 22:38 UTC, janosh commented on pymatgen/io/vasp/sets.py
> +class MatPESStaticSet(DictSet):
Inheriting from `DictSet` means `MatPESStaticSet.from_prev_calc` is no longer defined so the tests need to change.

2023-08-29 02:27 UTC, janosh commented on pymatgen/io/vasp/sets.py
> +class MatPESStaticSet(DictSet):
The tests are still failing. You can run them using

```py
pytest tests/io/vasp/test_sets.py -k TestMatPESStaticSet -vv
```

Requires `pip install pytest` if you haven't installed it yet. Should print sth like

```txt
___________ TestMatPESStaticSet.test_init ___________

self = <tests.io.vasp.test_sets.TestMatPESStaticSet testMethod=test_init>

    def test_init(self):
        # check if default INCAR settings are loaded
        default = MPStaticSet(self.struct)
        incar = default.incar
        # assert incar["GGA"] == "Pe"
        assert incar["ALGO"] == "Normal"
>       assert incar["EDIFF"] == 1.0e-05
E       assert 0.0012000000000000001 == 1e-05

tests/io/vasp/test_sets.py:747
```

2023-08-29 05:13 UTC, JiQi535 commented
I was not able to directly commit to this PR, so I opened #3280

2023-08-29 13:41 UTC, closed without merging