Adding alias `.to_file()` for `.to()` method of structures and molecules
materialsproject/pymatgen pull request #3356
Opened 2023-09-27 17:40 UTC by QuantumChemist

##Summary

I have noticed that many beginners (including myself a while ago) find it very unintuitive to write e.g. structures to a file by using .to(), especially with the .from_file() method counterpart. That's why I added aliases `to_file` for structures and molecules.

PS: This is the second attempt of #3354 as something went wrong there...

2023-09-27 17:45 UTC, janosh commented on pymatgen/core/structure.py
> +        return self.to(filename, fmt, **kwargs)
I think we can move this to `SiteCollection` so only need a single alias and forward both `*args` and `**kwargs`?

2023-09-27 17:50 UTC, shyuep commented
You don't actually need to write it this way. All that needs to be done is to add `to_file = to` and `write_file = to` in SiteCollection. That will create the aliases without so much code.

2023-09-27 18:02 UTC, QuantumChemist commented
> You don't actually need to write it this way. All that needs to be done is to add `to_file = to` and `write_file = to` in SiteCollection. That will create the aliases without so much code.

I know, that's how I started, but when I tried to call the alias in pycharm, it wouldn't give me the input hints and at least for me they are really important. If you think that's not necessary, then I can change it to the simple alias.

2023-09-28 16:44 UTC, janosh requested changes
We definitely need a test for the new alias.

2023-09-28 20:55 UTC, QuantumChemist commented
> We definitely need a test for the new alias.

Aye aye! 🫡

2023-09-30 16:06 UTC, QuantumChemist commented
hi @janosh I hope the tests are ok like that?

2023-09-30 17:00 UTC, janosh approved these changes
Thanks @QuantumChemist! 👍

2023-09-30 17:17 UTC, merged