Add `summary_stats` key to `Vasprun.potcar_spec`
materialsproject/pymatgen pull request #3434
Opened 2023-10-30 16:12 UTC by esoteric-ephemera

Given the new POTCAR validation introduced in [PR #3351](https://github.com/materialsproject/pymatgen/pull/3351), it makes sense to include a `summary_stats` key in the `Vasprun.potcar_spec` dict (from `io.vasp.outputs`). This will help with validation of outputs using the new summary stats method.

I also removed a few duplicate entries in the reference potcar_summary_stats.json.gz file used to perform validation. To keep the test files (`io.vasp.test_outputs.py` in particular) from getting unwieldy, I moved the reference `potcar_spec` lists to json files (`tests/files/test_io_vasp_update_potcar_*.json`).

2023-10-31 15:58 UTC, janosh requested changes

2023-10-31 15:58 UTC, janosh commented on pymatgen/io/vasp/potcar_summary_stats.json.gz
> I also removed a few duplicate entries in the reference `potcar_summary_stats.json.gz` file used to perform validation.

How come the file size increased?

2023-10-31 15:58 UTC, janosh commented on tests/files/test_io_vasp_update_potcar_1.json
Isn't this file redundant with `pymatgen/io/vasp/potcar_summary_stats.json.gz`? Maybe better to load the data from there and merge it into the rest of the POTCAR metadata directly in the test so we keep a single file to update if the validation scheme requires future changes.

2023-10-31 16:46 UTC, esoteric-ephemera commented on pymatgen/io/vasp/potcar_summary_stats.json.gz
I had to add a `symbol` key to every entry for compatibility with Vasprun's `potcar_spec`. If I take those fields out, the file size is 505 kb, so ~7 kb less than before

Taking out the symbol field from `potcar_spec` would have too many downstream consequences

2023-10-31 16:50 UTC, esoteric-ephemera commented on tests/files/test_io_vasp_update_potcar_1.json
Sorta: this is the output of `Vasprun.potcar_spec`, which has information contained in `pymatgen/io/vasp/potcar_summary_stats.json.gz` only if a potcar with matching spec is contained in the reference summary stats file.

Previously the titel and hash tags were static in the test as well because they're generated from vasprun.xml and POTCAR

There's not an easy way to make a dynamic test here because this checks vasprun.xml and not POTCAR alone

2023-10-31 17:04 UTC, matthewkuner commented
@esoteric-ephemera is there any chance you could add the ZVALs to the summary_stats.json file in this PR too? We talked about this a while ago offline

2023-11-01 21:25 UTC, janosh commented on tests/files/test_io_vasp_update_potcar_1.json
I don't understand the difficulty here (we do have `vasprun.xml` test files if that's what's needed?) but I'll take your word for it. 😄

2023-11-01 21:26 UTC, janosh approved these changes
@esoteric-ephemera Thanks for pushing the POTCAR validation all the way from conception to production! 👍

2023-11-01 21:27 UTC, esoteric-ephemera commented on tests/files/test_io_vasp_update_potcar_1.json
I do see what you mean now, let me fix this before proceeding!

2023-11-01 22:39 UTC, esoteric-ephemera commented on tests/files/test_io_vasp_update_potcar_1.json
Think it's good now! Can you give it a once over?

2023-11-01 22:58 UTC, merged