Add codespace container for reproducing issues
materialsproject/pymatgen pull request #3536
Opened 2023-12-31 13:34 UTC by DanielYang59

Tasks finished to resolve #2753:
- Added a codespace container configuration file.
- Added a brief guide to use codespace container for issue reproduction.
- Added link in issue template to encourage users to try this new workspace.

However I still need advice on handling user feedbacks, as I failed to identify any way to create a link or share a snapshot to an existing codespace, as @janosh suggested.

> We'd link this codespace in our issue template and invite people to launch it, copy-paste their code into it and then paste the link to the codespace into their issue.

The closest I could find currently is the [Live Share](https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace), which allows multiple users to work on a single codespace in real-time. But I don't think this is what we're looking for though. This would require the user to publicly share a link to a codespace and might have security risks.

So far the best solution to me still remains to run the code in the codespace, and **paste the output back to the issue** manually (until a feature such as sharing a snapshot is out). In doing so, we could help pre-configure the reproduction environment and information collection mechanisms, also avoiding all sorts of non-pymatgen issues (python not installed properly, outdated pymatgen or dependency, and so on).

2023-12-31 16:16 UTC, janosh requested changes

2023-12-31 16:16 UTC, janosh commented on .devcontainer/README.md
Shouldn't this markdown be part of the issue template?

2023-12-31 16:16 UTC, janosh commented on .devcontainer/create_codespace.png
Nice, very helpful for users. We don't need to check this file in though. Could you compress it, then upload it to a github issue? just drag and drop the file into the markdown area, no need to actually open the issue. GH will give you a link to the file on their servers which you can use anywhere.

2023-12-31 16:17 UTC, janosh commented
laos, could you rebase your branch onto pymatgen `master`?

2024-01-01 01:45 UTC, DanielYang59 commented
I'm really sorry @janosh. I must have been messing with commits trying to rebase and combine my commit history. Should I close this PR and reopen a new one?

2024-01-01 01:46 UTC, DanielYang59 commented on .devcontainer/create_codespace.png
Thanks. New hack learned.

2024-01-01 01:51 UTC, closed without merging