Adding Abinit magmoms from netCDF files to Structure.site_properties
materialsproject/pymatgen pull request #3936
Opened 2024-07-18 09:19 UTC by gbrunin

## Summary

In recent developments in Abinit, the variables `intgden` and `ratsph` have been added in the netCDF output files. These correspond to the computed integrated density around atoms and the integration radii. The former can be interpreted as the local magnetic moment on each atom. Since this is a useful quantity for, e.g., CHGNet model training, I have added them as `site_properties` of the `Structure` that is extracted from the netCDF file. If `intgden` is not found in the .nc file, nothing is added. 

Tagging @gmatteo to check this.

2024-07-19 14:21 UTC, gbrunin commented
This is ready to be reviewed. I don't know why ruff is failing, I did not make changes in io.vasp, io.aims and analysis.

2024-07-24 13:44 UTC, gbrunin commented
Hi @janosh, @shyuep, @mkhorton, whenever you have some time, this is ready to be reviewed. It would be great for us if these changes could be included in the next release, to facilitate developments in abipy (since this PR is fixing breaking changes). Thanks!

2024-07-24 13:57 UTC, janosh requested changes

2024-07-24 13:57 UTC, janosh commented on tests/files/io/abinit/Fe_magmoms_collinear_GSR.nc
`tests/files/io/abinit/Fe_magmoms_collinear_GSR.nc`  and `tests/files/io/abinit/Fe_magmoms_noncollinear_GSR.nc` are big files. are they actually needed for the test? if so, they should be compressed.

2024-07-24 15:15 UTC, gbrunin commented on tests/files/io/abinit/Fe_magmoms_collinear_GSR.nc
Hi, yes the files are necessary because they included the latest changes in the netCDF files in Abinit. I also totally understand the need to keep files as small as possible. I have compressed them, I hope it's enough.

2024-07-26 11:05 UTC, janosh commented on tests/files/io/abinit/28ni.paw
wow, the GSR files compressed to much smaller than expected. can we compress this file as well? sorry, should have mentioned this file in the first review

2024-07-26 13:01 UTC, gbrunin commented on tests/files/io/abinit/28ni.paw
done

2024-07-26 15:06 UTC, janosh approved these changes
thanks for this contribution @gbrunin! 👍

2024-07-26 15:07 UTC, merged