Fix `S101`, replace all `assert` in code base
materialsproject/pymatgen pull request #4017
Opened 2024-08-26 03:16 UTC by DanielYang59

### Summary

- Fix `S101`, replace all `assert` in code base

2024-08-29 06:42 UTC, janosh requested changes
thanks a lot for all this work @DanielYang59! 🙏 

will improve user experience a lot to get helpful error messages rather than a generic `AssertionError`. to make the messages more informative, i think it would be great to include the offending value/type in all `(Value|Type)Errors` (see 135f69ef7d for a fe examples)

2024-08-29 06:47 UTC, DanielYang59 commented
> thanks a lot for all this work @DanielYang59! 🙏

No problem. Thanks for reviewing!

> to make the messages more informative, i think it would be great to include the offending value/type in all `(Value|Type)Errors` (see [135f69e](https://github.com/materialsproject/pymatgen/commit/135f69ef7db4b1318c0882fd46e08d31204f4b86) for a fe examples)

That's a very sensible suggestion, I would implement this later :)

2024-08-31 03:20 UTC, DanielYang59 commented
Manually trace this link https://github.com/materialsproject/pymatgen/commit/135f69ef7db4b1318c0882fd46e08d31204f4b86 to the discussion on f-string, in case I want to get back to this thread.

2024-08-31 05:51 UTC, janosh approved these changes
excellent work! 🙏

2024-08-31 05:53 UTC, DanielYang59 commented on src/pymatgen/analysis/diffraction/xrd.py
> +            wavelength_type = type(wavelength).__name__
Ah, thanks a lot for fixing all those (`type(var).__name__` for name directly instead of `<class 'xxx'>`). I totally forgot about them.

2024-08-31 06:01 UTC, merged